services:
  api:
    container_name: api.bukiz.com
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env  
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@postgres:5432/${DATABASE_NAME}?schema=public"

  postgres: 
    container_name: bukiz.db
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_USER}
    ports:
      - "5432:5432"